micronaut:
  application:
    name: example-jdbc
#jackson:
#  bean-introspection-module: true

datasources:
  default:
    url: jdbc:oracle:thin:@100.1.1.51:1521:pro1
    username: website
    password: website
    driverClassName: oracle.jdbc.OracleDriver
    dialect: ORACLE

jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: none
#micronaut:
#  application:
#    name: example-jdbc
#jackson:
#  bean-introspection-module: true
#---
#datasources:
#  default:
#    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#    schema-generate: CREATE_DROP
#    dialect: H2
#jpa:
#  default:
#    properties:
#      hibernate:
#        bytecode:
#          provider: none
#        hbm2ddl:
#          auto: update
#micronaut:
#  application:
#    name: examples
#jackson:
#  bean-introspection-module: true
#
#datasources:
#  default:
#    url: jdbc:oracle:thin:@100.1.1.51:1521:pro1
#    username: website
#    password: website
#    driverClassName: oracle.jdbc.OracleDriver
##    dialect: ORACLE
##    driverClassName: oracle.jdbc.driver.OracleDriver
#
#jpa:
#  default:
#    properties:
#      hibernate:
#        bytecode:
#          provider: none
#        hbm2ddl:
#          auto: update